### ISSUE TITLE
Maximum dataset size?

### ISSUE THREAD

**Issue by Joleeo** [davidlvxin/TransC#10]
Hello,
I've successfully run your code on a truncated version of my dataset but am having issues on running it on the full version. Do you have a vague estimate for the maximum dataset size that I should be attempting?
Thanks

**Comment by davidlvxin** [comment]
I'm sorry, because of the problem of negative sampling, this code cannot run on very large data sets. The maximum data set size that can be run depends on the memory size of your device, so I cannot give an accurate estimate. But I guess that 3 times the size of the existing data set (YAGO39K) should be a possible upper bound. In the future, I will release the pytorch version of the code, which may be applicable to larger data sets.
