### ISSUE TITLE
have you tried NELL KG?

### ISSUE THREAD

**Issue by bagindokemas** [davidlvxin/TransC#8]
Dear Authors,

Today, I tried running NELL KG (http://rtw.ml.cmu.edu/rtw/) using TransC, and I found out that TransC needs a lot of time to train the model (I started training the dataset using 95GB RAM machine since 7 hours ago and until I wrote this Issue, TransC still doing the training). 
The size of NELL KG that I feed to the training process is small (38,806 triples), with 1188 concepts and 895 relations. 
My questions are as follows:
1. Have you test running NELL KG with TransC ?
2. Does the length of the concept label and also the length of the relation label affect the training process of TransC? For instance, one of the concept label in NELL KG is academicfieldusedbyeconomicsector and one of the relation label in NELL KG is inverseofastronautwasonamissionwithastronaut .

Thank you very much.
Kemas Wiharja

**Comment by davidlvxin** [comment]
1. I have not tested on the NELL data set. Because of the negative sampling strategy, this code runs slowly on large-scale data sets. I will release the pytorch version of the code in the future, which may solve this problem.
2. The label information of concepts and relations does not affect the operating efficiency of the model, because the transC model does not consider label information.
